import           Control.Exception
import           Lib

main :: IO ()
main =
  putStrLn "test ok"
